### PR TITLE
Fix font awesome icons for far and fas sets

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Fix FA icons on `<p>` tags for `far` and `fas` sets

# Need Review By (Date)
- February 2022

# Urgency
- medium

# Steps to Test
1. checkout this branch
2. clear browser caches
3. Use the following html and verify the icons display
```
<p class="fab fa-adn">FAB</p>

<p class="fas fa-address-book">FAS</p>

<p class="far fa-address-book">FAR</p>

<div class="fab fa-adn">FAB</div>

<div class="fas fa-address-book">FAS</div>

<div class="far fa-address-book">FAR</div>
```

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by jenbreese** [comment]
@pookmish So this works. My question is that I went through and made samples of all the tags you can add the FA classes too: https://amptesting.sites.stanford.edu/interior-page/test-wysiwyg/social-media-icons-using-text-area-wysiwyg  Do we want to make sure those all work? Or do we want to pick and choose? For example, I can see why on an `li` it would be useful to put the icon.

**Comment by pookmish** [comment]
Well it certainly wouldn't hurt to check other elements. if you wish to add more selectors, feel free to do so.

**Comment by jenbreese** [comment]
> Well it certainly wouldn't hurt to check other elements. if you wish to add more selectors, feel free to do so.

Hi @pookmish, I added more elements that are likely candidates to have the icons on.  Thank you for looking.

**Comment by jenbreese** [comment]
Hi @pookmish I realized it was assigned to me to merge but I think you should take a look too just since I made a few changes. Thank you!

**Comment by pookmish** [comment]
Thanks @jenbreese, I'm sure it can't hurt to have more selectors in there. The likelihood of them being used is minimal anyways.
Go ahead and merge when you're ready.

**Review by jenbreese — APPROVED** [review]
GTG

**Pull request merged**
