### PR TITLE
D8CORE-941: drop cap styles

### PR DESCRIPTION
**Pull request by cjwest**
# READY FOR REVIEW 

# Summary
WYSIWYG tweaks
_See ticket:  https://stanfordits.atlassian.net/browse/D8CORE-941_

# Needed Review By (Date)
- Sprint end

# Urgency
- Fixes broken stuff
- Not Urgent

# Steps to Test

- Checkout this branch
- Within the WYSIWYG, create a paragraph with a drop-cap style
- save 
- verify it's baseline is on the same baseline as the second line of text in the paragraph, and it's about as tall as those first two lines:

Screen Shot 2020-01-08 at 12 00 47 PM

# Affected Projects or Products
- D8Core (https://github.com/SU-SWS/acsf-cardinalsites)

# Associated Issues and/or People
## Related JIRA ticket(s)
https://stanfordits.atlassian.net/browse/D8CORE-941

## More Information
By reducing the line-height and increasing the margin-top, I got Firefox and Chrome to look the same.

## Folks to notify
`@sherakama` 
`@kerri-augenstein`

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by sherakama** [comment]
What do you need help with?

**Comment by cjwest** [comment]
@sherakama, 
I haven't found a way for the Drop Caps to line up in Firefox. Do you have any suggestions?

**Comment by sherakama** [comment]
This article seems to document the troubles you have: https://www.smashingmagazine.com/2012/04/drop-caps-historical-use-and-current-best-practices/#method-4-first-child-first-letter

From what the article states, you won't be able to get consistent alignment from browsers without introducing a span tag to wrap the first character. They suggest if you don't want to introduce the markup requirement to augment the `First-Child:First-Letter` method with some javascript to get consistency across all browsers.

**Comment by sherakama** [comment]
Here is an article about the Firefox alignment issue with drop caps: https://www.sitepoint.com/a-simple-css-drop-cap/

**Comment by cjwest** [comment]
@sherakama,
Thanks for your help. By increasing the margin-top and decreasing the line-height, I found a compromise that works on Firefox and Chrome.

**Pull request merged**
