### PR TITLE
D8CORE-1024 Template and styles for login portal style page

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Create a portal style login page.
- Some of the scss might need some adjustment to be inline with decanter formats

# Need Review By (Date)
- 2/12

# Urgency
- medium

# Steps to Test
1. checkout this branch. 
1. checkout https://github.com/SU-SWS/stanford_ssp/pull/83
1. checkout https://github.com/SU-SWS/stanford_profile/pull/82
1. `drush cim; drush cr`
1. navigate to `/user/login` as anonymous.
1. validate it looks like a portal login page.
1. add `$config['stanford_ssp.settings']['hide_local_login'] = TRUE;` to a settings.php like `local.settings.php` file
1. clear cache
1. reload `/user/login`
1. validate it looks trimmed down and clean.

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

https://github.com/SU-SWS/stanford_ssp/pull/83
https://github.com/SU-SWS/stanford_profile/pull/82

### CODE REVIEW

**Comment by sherakama** [comment]
@pookmish the page is looking good.

@kerri-augenstein are we allowed to remove the global footer from this page? The links to the policies in the footer seem to be rather important on this page.

**Comment by sherakama** [comment]
Screen Shot 2020-02-05 at 10 36 44 AM

The absolute positioning and variance to the form options need a bit of work.

**Comment by sherakama** [comment]
The hover on the button fades to black and matches the background of the centered container.

**Comment by sherakama** [comment]
Screen Shot 2020-02-05 at 10 46 18 AM

**Comment by pookmish** [comment]
should be good. just depending on the answer from @kerri-augenstein

**Comment by sherakama** [comment]
A couple more revisions

The Gif

**Comment by pookmish** [comment]
well those aren't available on our prod sites. but i guess since this theme could be used anywhere, probably should add them

**Comment by sherakama** [comment]
If you offer it you must support it. Kind of like a public method in a class. You are committed to ensuring it works.

**Comment by kerri-augenstein** [comment]
@sherakama @pookmish, 

Ah, if we think that's necessary here, I'll totally defer to y'all. Sounds great to add in the global footer!!!

**Pull request merged**
