### PR TITLE
D8CORE-2592: removing the id that isn't used on sub menus

### PR DESCRIPTION
**Pull request by jenbreese**
# NOT READY FOR REVIEW
I chatted with Shea last night and I should make the ids unique instead. So pulling this back to adjust. Thanks!

# Summary
- Remove the duplicate ID's that happens on submenus for the mobile/responsive view.

# Review By (Date)
- Wednesday 10/21

# Urgency
- Med

# Steps to Test

1. Pull in this change.
2. Create menu links to have sub menus on main pages.
3. change to the mobile view. 
4. Verify that that there are no more id='su-acs-

# Affected Projects or Products
- This is done on Stanford Basic and we also need it on SOE since that is where it was found.

# Associated Issues and/or People
- D8CORE-2592
- @cjwest 

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Review by pookmish — DISMISSED** [review]
Seems to do what its supposed to do.

**Comment by pookmish** [comment]
A couple CC issues and then this can be merged.

**Comment by jenbreese** [comment]
@pookmish can you comment on the the parentIndex variable? As I nest menus deeper, I get repeated IDs.  You can see in the screenshot.
Screen Shot 2020-10-20 at 10 28 24 AM

**Comment by jenbreese** [comment]
@pookmish Your last commit fixed it for me. thank you!

**Review by pookmish — APPROVED** [review]

**Pull request merged**
