### PR TITLE
 HSD8-89 Add additional lines in the lockup

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Add additional lines in the theme settings to allow for more flexible lockups.

# Needed By (Date)
- When you can

# Urgency
- low

# Steps to Test

1. Checkout this branch
1. clear cache
1. go into the theme settings
1. add some text to the lockup settings
1. save and view result on the front end.
Styling will still be needed.

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by sherakama** [comment]
This looks ok to me. @josephgknox can you review as well.

**Comment by pookmish** [comment]
Big Joe is out for the week. Its not critical at this time for H&S at least

**Comment by sherakama** [comment]
Ok, feel free to merge when ready but I suspect Joe will want to give it some styling love.

**Comment by pookmish** [comment]
Ok merging this and creating a ticket to style the extra line

**Pull request merged**
