### PR TITLE
Update Decanter to v 6.1.1 and compile.

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW 

# Summary
- Updates Decanter to version 6.1.1

# Review By (Date)
- Sept 4th

# Urgency
- High

# Steps to Test

1. Review code
2. Check out this branch on your local build
3. Review the alerts to validate new styles are there.

### CODE REVIEW

**Comment by jenbreese** [comment]
I found a couple of problems with the grey and gold warnings. I will fix those in Decanter. In Stanford Basic theme, the blue/info had an override that needs to be removed. I'll fix that as well.

**Comment by jenbreese** [comment]
@sherakama Could you take a look at this one? Maybe I should have made a new branch/pull request?

**Review by sherakama — COMMENTED** [review]
GTG

**Review by jenbreese — APPROVED** [review]
GTG

**Pull request merged**
