### PR TITLE
D8CORE-3441: a11y changes for dropdowns

### PR DESCRIPTION
**Pull request by imonroe**
# READY FOR REVIEW

# Summary
- A11y changes for dropdowns.
- Adds a hover state to the `su-nav-toggle` component.
- Switches the arrow from red to black.

# Review By (Date)
- code freeze

# Urgency
- needed for 2.0.0

# Steps to Test

1. Checkout branch
2. clear caches
3. create drop down menu items in the navigation menu.
4. Observe the state of the carets in the navigation menu as you hover and click.

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- D8CORE-3441

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by imonroe** [comment]
@jenbreese and @katrialesser -- This solution works, but it's not awesome.
- it correctly changes the caret to black upon hover, and it adds an underline (border-bottom, actually).
- it correctly removes the underline when you expand a dropdown.
- However, when you CLOSE the dropdown, it changes to `aria-expanded=false` too quickly, and you get a flash of an underline that looks janky. 

I couldn't find a way to fix that.  Any ideas?

**Comment by jenbreese** [comment]
@imonroe I'll take a look shortly. I'm working on a different bug.

**Comment by jenbreese** [comment]
Hi @imonroe, It functions fine.  There is a line overhanging the menu now.
Screen Shot 2021-02-04 at 2 46 19 PM

**Comment by imonroe** [comment]
That might be something I can correct with an `overflow:hidden`.  trying that now.

**Comment by imonroe** [comment]
Yep, that did it.  

image

**Review by jenbreese — APPROVED** [review]
Looks good to me.

**Pull request merged**
