### PR TITLE
D8CORE-144: Stanford Basic Preliminary

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW

# Summary
- Retroactive review
- Review everything and validate tests.

# Needed By (Date)
- End of next sprint (Sept 28).

# Urgency
- Medium

# Steps to Test

**SETUP:**
1. Install `stanford_profile` and ensure stanford_basic is set as the default theme

- [ ] **Config:**
1. Review theme-settings.php and all of the configuration including the schema  in /config
2. Review `admin/appearance/settings/stanford_basic` form and configuration options
3. Run tests `lando blt tests:behat:run -D behat.paths=${PWD}/docroot/themes/`

- [ ] **File Structure:**
1. Review the overall file structure and organization for questions, comments, and concerns.

- [ ] **Javascript/SCSS Compiler**
0. Review webpack.config.js file for settings and configuration
1. Run `nvm use`
2. Install npm packages `npm install`
3. Run a build `npm run build`
4. Review README.md for documentation

- [ ] **Review Javascript**
1. Review files in `/src/js/*` for structure formatting and contents.

- [ ] **Review SCSS**
1. Review files in `/src/scss/*` for structure formatting and contents.

- [ ] **Review templates**
1. Review files in `/templates/*` for structure formatting and contents

- [ ] **Review tests**
1. Review tests for whether or not they meet the GE standard.

- [ ] **Review the other theme files**
- stanford_basic.breakpoints.yml
- stanford_basic.info.yml
- stanford_basic.libraries.yml
- stanford_basic.theme

# Affected Projects or Products
- Pretty much everything

# Associated Issues and/or People
-  D8CORE-144

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by pookmish** [comment]
Some options appear broken:
Option Q: failed behat
Option R: failed behat
Option S: failed behat & height issues option s
Also some spacing might be needed at some point

Want me to add the caravan to this PR?

**Comment by sherakama** [comment]
Sure, if that work is in a GE place.

**Comment by sherakama** [comment]
Also, agreed that the masthead area needs some love with the vertical spacing.

**Comment by pookmish** [comment]
ok behat are passing now. and i think caravan will need some adjustments to enable a theme

**Comment by sherakama** [comment]
What did you change to get the behat tests to pass?

**Comment by pookmish** [comment]
:man_shrugging: they just worked. at first i added `@javascript` so i could visually see the results. that failed.

**Comment by pookmish** [comment]
yeah add javascript at the top of the file. it fails reliably

**Comment by pookmish** [comment]
there might be some css/js that is hiding parts?

**Comment by sherakama** [comment]
What is the error?

**Comment by pookmish** [comment]
```
Then I should see "Variant Q - Line 3"                       # Drupal\DrupalExtension\Context\MinkContext::assertPageContainsText()
      The text "Variant Q - Line 3" was not found anywhere in the text of the current page.
```

**Comment by pookmish** [comment]
did you want to review the behat with javascript turned on? just for validation?

**Comment by sherakama** [comment]
That is low priority, I'll create a ticket for it for later.

**Comment by sherakama** [comment]
@boznik please go through the testing steps for this PR as well so that you become familiar with the theme and can raise any concerns or questions early as most of this theme has not been reviewed and has been completed skunkworx style.

**Pull request merged**
