### PR TITLE
D8CORE-2490: Alert Component Updates

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW 

# Summary
- Updates to NPM Packages
- Updates to Alerts

# Review By (Date)
- Sept 3rd

# Urgency
- 10/10

# Steps to Test

1. Review code
2. Do a full build of cardinalsites or lelandd8 on the D8CORE-1609 branch of their repo
3. Clear all caches through the UI by logging in and using the admin menu links
4. Review style of new status (blue) alert
5. Click on the dismiss button
6. See alert go away
7. Navigate to `/patterns/alert` and see each alert style

Run a build of this branch. 
```
nvm use
npm install
npm run publish
```

Validate no changes to repo css.

# Affected Projects or Products
- D8CORE 
- SOE
- Adapt

# Associated Issues and/or People
- D8CORE-1609
- D8CORE-2490

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by jenbreese** [comment]
@cjwest When you look at this, I had a question about the links on the alerts. On the red alert, is the hover state accessible? To me, I find it hard to read.

**Comment by jenbreese** [comment]
@cjwest It passed the HTML validator.  The VisBug showed problems with the hover color. Do you know what color we should use or should I chat with @ishahism ?
Screen Shot 2020-09-02 at 10 55 45 AM

**Comment by ishahism** [comment]
We can use $su-color-white for the hover state on the action link.

**Comment by cjwest** [comment]
Hi Jen,
Yeah, we have a problem in the link hover. It completely disappears. I wonder if it should just be a white underline?

Screen Shot 2020-09-02 at 10 59 38 AM


Thank you for pinging me on this PR! I was just going through tickets to find what needed my review.
FYI, there's the A11y-test label. It's super helpful for me to find tickets for A11y review.

**Comment by cjwest** [comment]
@jenbreese 
Is this something we should address here?
Screen Shot 2020-09-02 at 11 11 54 AM

**Comment by cjwest** [comment]
Screen Shot 2020-09-02 at 11 20 52 AM

**Comment by jenbreese** [comment]
@cjwest I was looking and it is a component in Decanter.  Here is where the SASS lives:
https://github.com/SU-SWS/decanter/tree/master/core/src/scss/components/alert

So the twig files and everything here looks fine. I would think we'd change it in Decanter rather than override in our themes since Decanter is a public offering and we want to be sure it is accessible. @sherakama What do you think?

**Comment by ishahism** [comment]
It looks like Decanter is using the $su-color-fog for the hover state on "critical (red)" alert messages. I think we can use that in SU basic as well.

**Comment by ishahism** [comment]
These are the colors that Decanter is using for hover state on alert messages. We can use the same for SU basic

- $su-color-fog for the hover state on "success (green), information (blue), and critical (red)"

- $su-color-black for the hover state on "plain (gray), warning (yellow)"

**Comment by ishahism** [comment]
Hi @cjwest, from the Decanter website, the hover state on action links should use $su-color-fog the success (green), information (blue), and critical (red) options. I will that support readability? 

Also, instead of white can we use $su-color-bright-red or $su-color-bright-blue on the "plain (gray)" options?

**Comment by cjwest** [comment]
One thing I'm having trouble with on these alerts is that from what I can see, the level of the alert is solely indicated by color. There is no other information that indicates whether it is an error or success. Could I be missing something?

**Comment by ishahism** [comment]
Hi @cjwest, I understand your point, but I believe the text in within the alert message should help community the "level of alertness". These are global alerts, not error messages, so it would be up to the site owners to provide the appropriate information.

**Comment by jenbreese** [comment]
@cjwest and @ishahism, I spoke to @sherakama and he said that @bhavikasolanki did the design for alerts so I should check with her. Thank you all!

**Review by jenbreese — APPROVED** [review]
This part looks good. There is the hover issue but that will be fixed in Decanter with another pull request.

**Comment by bhavikasolanki** [comment]
Hi all, let's move forward with removing the color change for links upon hover and indicate hover state with just the underline. We can do this for all alerts.

**Pull request merged**
