### PR TITLE
D8CORE-4234: change to how the onEsc.js works

### PR DESCRIPTION
**Pull request by jenbreese**
# READY FOR REVIEW

# Summary
- Changing how the the esc works when using the `tab` key to navigate.
- There is a video in the ticket of it working as I expect. 

# Review By (Date)
- 11/15

# Criticality
- Accessibility request
- Effects all sites using SBT and drop down menus enabled.

# Urgency
- Normal

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Rebuild Cache and import config `drush cr ; drush ci`
3. It's a good idea to clone down the amptesting site because it has lots of menus to play with. 
3. Navigate to a site/page with the menus enabled and lots of sub menus. 
4. Verify when you press `esc` the menu closes. On the last one when it closes, it will close the whole menu. Please take a look a the video for an example with my commentary.

### Site Configuration Sync

- Is there a config:export in this PR that changes the config sync directory? NO

## Front End Validation
- [ ] Design is approved by @ user?
- [ ] HTML validation: Is the markup using the appropriate semantic tags and [passes validation](https://validator.w3.org/nu/)? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Cross-browser testing: Has been performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Automated accessibility: Scans performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Manual accessibility: Manually tested? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Stanford Basic Theme.

# Associated Issues and/or People
- [D8CORE-4234](https://stanfordits.atlassian.net/browse/D8CORE-4234)
- @cjwest 

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Review by imonroe — CHANGES_REQUESTED** [review]
This works as described, but I'm still feeling like the interaction is a bit inconsistent.  Could we have @cjwest try it out on a system herself and confirm this is the way it should work before we merge?

**Comment by jenbreese** [comment]
@cjwest  is out right now. Let me see if there is any office hours or time SODA can review it.

**Comment by imonroe** [comment]
Sounds good.  I just want to ensure everyone knows what to expect.

**Comment by jenbreese** [comment]
@imonroe this week the team is out at the accessibly training in Denver so there isn't Accessibility office hours this week. The next ones are 11/23 which misses our code freeze. Should this move to the next release?

**Comment by imonroe** [comment]
Maybe we can discuss in standup?

**Comment by imonroe** [comment]
Per conversation in standup, we're going to merge this since it's an improvement, and we'll circle back during code freeze when the a11y folks are available for consult.

**Review by imonroe — APPROVED** [review]
approved.

**Pull request merged**
